name: Auto Fork and Callback

on:
  schedule:
    - cron: '0 0 */3 * *'  # 每3天执行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  auto-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Fork target repo
        id: fork
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/senshinya/MoonTV/forks)

          echo "$response"
          
          if echo "$response" | grep -q '"full_name"'; then
            echo "fork_success=true" >> $GITHUB_OUTPUT
          else
            echo "fork_success=false" >> $GITHUB_OUTPUT
          fi

      - name: Call callback API if fork success
        if: steps.fork.outputs.fork_success == 'true'
        run: |
          curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/ef5b35c2-9ea7-4e71-9533-cb8253f140ce \
            -H "Content-Type: application/json" \
            -d '{"status":"success","repo":"<your-forked-repo>"}'
